### ISSUE TITLE
Users can neither create account nor login

### ISSUE THREAD

**Issue by EmmanuelObua** [familytree365/frontend#143]
![Screenshot from 2021-05-28 10-32-43](https://user-images.githubusercontent.com/45915845/119947140-17ce4a00-bfa0-11eb-8531-e6c3826c3a57.png)

**Comment by curtisdelicata** [comment]
We are looking into this but do you have any suggestions?

**Comment by EmmanuelObua** [comment]
> We are looking into this but do you have any suggestions?

Everything looks fine as far as auth is concerned. I shall have views once I can login

**Comment by curtisdelicata** [comment]
Pull request welcomed if you find a solution.

**Comment by curtisdelicata** [comment]
Fixed.
