### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by zakariaarrid** [familytree365/frontend#187]
**Describe the bug**

After installing modules , and npm run dev , the error appears

**ERROR in ./node_modules/d3-dag/bundle/d3-dag.esm.min.js 14:9934
Module parse failed: Unexpected character '#' (14:9934)**

**Optional info**

OS: [Ubuntu]
Browser: [chrome]

**Comment by curtisdelicata** [comment]
d3 usage is pending upgrade for pedigree tree. pull requests are welcome.

**Comment by curtisdelicata** [comment]
Fixed.
